### ISSUE TITLE
Error on compiling 

### ISSUE THREAD

**Issue by sheldonGordon** [SmittyHalibut/EleksTubeHAX#34]
Hello guy,

I have that error on compiling.

In file included from D:\EleksTubeHAX-main\EleksTubeHAX\GLOBAL_DEFINES.h:14:0,
                 from D:\EleksTubeHAX-main\EleksTubeHAX\ChipSelect.h:4,
                 from D:\EleksTubeHAX-main\EleksTubeHAX\ChipSelect.cpp:1:
C:\Users\aurelien\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.4\cores\esp32/Arduino.h:183:12: error: 'std::round' has not been declared
 using std::round;
            ^
In file included from D:\EleksTubeHAX-main\EleksTubeHAX\GLOBAL_DEFINES.h:14:0,
                 from D:\EleksTubeHAX-main\EleksTubeHAX\Buttons.h:4,
                 from D:\EleksTubeHAX-main\EleksTubeHAX\Button.cpp:1:
C:\Users\aurelien\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.4\cores\esp32/Arduino.h:183:12: error: 'std::round' has not been declared
 using std::round;
            ^
In file included from D:\EleksTubeHAX-main\EleksTubeHAX\GLOBAL_DEFINES.h:14:0,
                 from D:\EleksTubeHAX-main\EleksTubeHAX\Backlights.h:4,
                 from D:\EleksTubeHAX-main\EleksTubeHAX\Backlights.cpp:1:
C:\Users\aurelien\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.4\cores\esp32/Arduino.h:183:12: error: 'std::round' has not been declared
 using std::round;
            ^
In file included from D:\EleksTubeHAX-main\EleksTubeHAX\GLOBAL_DEFINES.h:14:0,
                 from D:\EleksTubeHAX-main\EleksTubeHAX\Clock.h:5,
                 from D:\EleksTubeHAX-main\EleksTubeHAX\Clock.cpp:1:
C:\Users\aurelien\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.4\cores\esp32/Arduino.h:183:12: error: 'std::round' has not been declared
 using std::round;
            ^
In file included from C:\Users\aurelien\AppData\Local\Temp\arduino-sketch-A90A66D64D900CF2FECB49B5F6C4D1C7\sketch\EleksTubeHAX.ino.cpp:1:0:
C:\Users\aurelien\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.4\cores\esp32/Arduino.h:183:12: error: 'std::round' has not been declared
 using std::round;
            ^

exit status 1

Compilation error: exit status 1

Can you give me?

**Comment by SmittyHalibut** [comment]
Hmm..  Last time I played with this was before Arduino 2.0 was released.  Does that `esp32/2.0.4/` in the paths mean you're using Arduino IDE 2.0?

It's saying it can't find `std::round()` which is being referenced in Arduino.h??!

It sounds like there's some incompatibility between the ESP32 support and your version of Arduino.  Make sure you don't have any pending updates in your Boards or Libraries.

A quick `grep` confirms our code doesn't use `std::round()` anywhere.

**Comment by aly-fly** [comment]
This code is confirmed to work with Arduino 1.8.
From my quick experience with some other project I can confirm that Arduino 1.8 and 2.0 are not fully compatible, also ESP32 libraries were updated. For me the I2C port stopped working on 2.0 while everything was fine on 1.8.

**Comment by sheldonGordon** [comment]
I deleted all files on 2.0, I have reinstall on 1.8.13 and its OK.
Just i have a little other problem, my number display is horizontal instead of vertical.
Where it is possible to change that its code?
THX

**Comment by aly-fly** [comment]
Hm, so you have clock mounted vertically or you see rotated (and cropped) images?

**Comment by sheldonGordon** [comment]
![IMG_20230110_093950172_HDR](https://user-images.githubusercontent.com/47449935/211502412-297d3d3c-b33e-4c8b-938f-bd77fea719bd.jpg)

**Comment by sheldonGordon** [comment]
I pushing the default images in data folder
And i have compiled with HARDWARE_SI_HAI_CLOCK

**Comment by aly-fly** [comment]
Interesting.  The person I made SI-HAI version for originally, didn't report any such issues.
Probably there is a flag in the eTFT driver chip initialization function to set orientation. I am not too familiar with LCD driver chips. You can dig through eTFT libraries or Google and see if you can pinpoint how to rotate the screen.

**Comment by sheldonGordon** [comment]
![IMG_20230110_114334498_HDR](https://user-images.githubusercontent.com/47449935/211530818-4368b5d4-a5b3-4c13-9330-c6ab0cca1146.jpg)
The image is now in the right direction, but I do not understand the problem there

**Comment by sheldonGordon** [comment]
in TFTs.h i have just added `setRotation(3)` in line 40
`void enableAllDisplays()           { digitalWrite(TFT_ENABLE_PIN, HIGH); enabled = true; setRotation(3);}`

**Comment by aly-fly** [comment]
Try to exchange display Length and Width values...

**Comment by sheldonGordon** [comment]
doesn't work that reboot all 3 secondes.
maybe the ST7789_DRIVER driver is not good for me?

**Comment by aly-fly** [comment]
Try to examine the LCD display, any text you can find on the display itself or orange flex cable is useful. 
If display driver is wrong, displays will be completely black.
I don't have much experience with LCDs, try Arduino forums or Reddit...

**Comment by GHDESON** [comment]
![EleksTubeIPS_with_EleksTubeHAX](https://user-images.githubusercontent.com/26712823/214116733-50674381-62e6-4317-8c8a-31a1137e98ff.jpg)
I have a similar problem with:
EleksTubeIPS Docker v6.1.11
Arduino 1.8.19
NTPClient by Fabrice Weinberg (v3.2.0)
Adafruit NeoPixel by Adafruit (v1.8.0)
DS1307RTC by Paul Stoffregen (v1.4.1) *other developer?
TFT_eSPI by Bodmer (v2.3.61)
Time by Paul Stoffregen (v1.6.0) *other developer?
PubSubClient by Nick O'Leary (v2.8.0)
ArduinoJson by Benoit Blanchon (6.19.4)

**Comment by aly-fly** [comment]
Please write down all the details and text you can find on the LCD panels, including on or below the orange flat cable (unplug the FFC connector on the backside).

**Comment by GHDESON** [comment]
EleksTube IPS
NFP114H-03AF

**Comment by aly-fly** [comment]
nothing else? like starting with "ST"? 
This is the only reference I was able to find: IPS 1.14 Inch 135RGBX240 TFT ST7789 8 pin SPI HD 262k **FP-114H0**1A LCD
Looks like the defines for the build are okay. Maybe some small details are not correct for this display type... Or for the start you can try to lower the SPI clock frequency if it helps.

**Comment by GHDESON** [comment]
I also looked at another LCD. No, unfortunately nothing more.

**Comment by GHDESON** [comment]
When I press the keys, text appears in the lower area, this is only half-readable from the right, the orientation seems to be wrong.

**Comment by sheldonGordon** [comment]
i have a reference for LCD is "hd114001 XH"
@GHDESON you create a backup of the original firmware?

**Comment by GHDESON** [comment]
Yes, I have made a backup of the firmware.

**Comment by sheldonGordon** [comment]
have you tried your backup?
if it works i would like to get it back please

**Comment by GHDESON** [comment]
The original firmware is also available here https://github.com/SmittyHalibut/EleksTubeHAX/tree/main/original-firmware . However, the MAC address must be adapted, see 
https://github.com/SmittyHalibut/EleksTubeHAX/blob/main/original-firmware/README.md .

**Comment by GHDESON** [comment]
Is this page https://www.alibaba.com/product-detail/IPS-1-14-Inch-135RGBX240-TFT_1600462605851.html helpful?

In the bluish picture https://s.alicdn.com/@sc04/kf/Hddc955a8920546939237bd9769e86fa4v/230489091/Hddc955a8920546939237bd9769e86fa4v.jpg , I think it says exactly this type (NFP114H-03AF) designation on the cable.

**Comment by GHDESON** [comment]
Is the ST7789V2, 8Pin, 135x240 data helpful for troubleshooting the half and rotated display?

**Comment by sheldonGordon** [comment]
i think i will change the screens with those on alibaba

**Comment by GHDESON** [comment]
I wouldn't do that, it's exactly those that create the problem with the half and rotated displays for me.

**Comment by GHDESON** [comment]
I have a similar problem with:
EleksTubeIPS Docker v6.1.11
Arduino 1.8.19
NTPClient by Fabrice Weinberg (v3.2.0)
Adafruit NeoPixel by Adafruit (v1.8.0)
DS1307RTC by Paul Stoffregen (v1.4.1) *other developer?
TFT_eSPI by Bodmer (v2.3.61)
Time by Paul Stoffregen (v1.6.0) *other developer?
PubSubClient by Nick O'Leary (v2.8.0)
ArduinoJson by Benoit Blanchon (6.19.4)

**Comment by bitrot-alpha** [comment]
I wasn't able to even get the code to compile on Arduino IDE 1.8.19 and the library versions in the readme. I've submitted a PR (#50) with updates to the code. These updates allow for compiling with ESP32 2.0.X, the latest available libraries, and IDE 1.8.19.

If you're still interested, you can try my fork and see if anything improves.

**Comment by sheldonGordon** [comment]
hi @bitrot-alpha, I just tried with your changes. unfortunately that doesn't work either.
Thanks for your help though

**Comment by shyne99** [comment]
For those still looking for a solution to this, I have the following clock EleksTubeIPS Docker v6.1.11 and also had the glitchy screen thing. 

In order to fix it, I juste had to edit the library file User_Setup_Select.h of TFT_eSPI library and REMOVE the line `#include <User_Setup.h>`

The file should only have the include to GLOBAL_DEFINES.h inside the `#ifndef USER_SETUP_LOADED ... #endif` block. 

I had a very hard time to have a working firmware on this, first because the actual master branch does not compile and I had to use @bitrot-alpha fork (thank you by the way), and second because SPIFFS upload tool is just not working on arduino 2.X and had to revert to arduino 1.8, then this.... 

To be honest the README says that you should add the include to the project Global defines, it says nothing about removing the previous one in place.

**Comment by aly-fly** [comment]
True, Arduino IDE 2 does not work correctly. Version 1.8 must be used.

**Comment by aly-fly** [comment]
Fixed in my fork. Will be merged into this repo a bit later.

**Comment by GHDESON** [comment]
It works now with the pre-built firmware.
